arch = [
    "alpine",
    "argc",
    "asciinema",
    "bat",
    "bc",
    "boxes",
    "broot",
    "chezmoi",
    "cp437",
    "cpuburn",
    "daktilo",
    "ddgr",
    "devtoolbox",
    "dict-git",
    "diskonaut",
    "element",
    "eza",
    "f3",
    "fd",
    "file-roller",
    "frogmouth",
    "gcalcli",
    "gdu",
    "geekbench",
    "glmark2",
    "googler",
    "gpart",
    "gping",
    "hardinfo2",
    "hdparm",
    "hyperfine",
    "id3v2",
    "intel-gpu-tools",
    "lsd",
    "mesa-utils",
    "miller",
    "minicom",
    "mtr",
    "navi",
    "nodejs-how2",
    "ocrmypdf",
    "perl-image-exiftool",
    "phoronix-test-suite",
    "procs",
    "rar",
    "sad",
    "sd",
    "sendmail",
    "sharutils",
    "smem",
    "speedtest-cli",
    "stress",
    "sttr-bin",
    "sysbench",
    "testdisk",
    "textual-paint",
    "thefuck",
    "timidity++",
    "translate-shell",
    "units",
    "yt-dlp",
    "zoxide",
]

