arch = [
    "acme",
    "audacious",
    "autoconf",
    "autoconf-archive",
    "automake",
    "binutils",
    "binutils-ia16",
    "bison",
    "bitwarden",
    "blanket",
    "brave-bin",
    "bucklespring",
    "cc65",
    "ccache",
    "chibi-scheme",
    "cht.sh-git",
    "clang",
    "clisp",
    "cmake",
    "cool-retro-term",
    "csvkit",
    "ctags",
    "diffutils",
    "djgpp-binutils",
    "djgpp-djcrx-bootstrap",
    "djgpp-gcc",
    "freebasic",
    "gcc",
    "gcc-ia16",
    "glibc",
    "gmp",
    "gnuplot",
    "go",
    "gparted",
    "gpp",
    "graphviz",
    "guile",
    "hq",
    "htmlq",
    "ipython",
    "jq",
    "jqp",
    "lazygit",
    "lazyjournal",
    "libedit",
    "libmpc",
    "m4",
    "meld",
    "mpfr",
    "mplayer",
    "mpv",
    "nasm",
    "openwatcom-v2",
    "pandoc-bin",
    "papers",
    "patch",
    "plantuml",
    "racket",
    "regina-rexx",
    "regina-rexx-doc",
    "ruby",
    "ruby-lsp",
    "sbcl",
    "tass64",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-latexextra",
    "texlive-pictures",
    "translate-shell",
    "vasm",
    "vlang",
    "vlc",
    "x48ng",
    "ymuse-bin",
    "yq",
    "zlib",
]

