arch = [
    "7zip",
    "acpi",
    "aha",
    "arch-wiki-docs",
    "aspell-en",
    "auto-cpufreq",
    "bandwhich",
    "barrier",
    "barrier-headless",
    "bind",
    "bluez",
    "bluez-utils",
    "bpytop",
    "brightnessctl",
    "btop",
    "bzip2",
    "cifs-utils",
    "cndrvcups-lb-bin",
    "coolercontrol-bin",
    "cups",
    "debugedit",
    "direnv",
    "dos2unix",
    "dosfstools",
    "duf",
    "emacs",
    "exfat-utils",
    "expac",
    "fastfetch",
    "firewalld",
    "flatpak",
    "fwupd",
    "fzf",
    "gvfs-smb",
    "helvum",
    "hfsprogs",
    "htop",
    "hw-probe",
    "id3lib",
    "iftop",
    "imagemagick",
    "inxi",
    "iperf",
    "ispell",
    "keychain",
    "kitty",
    "languagetool",
    "lhasa",
    "light",
    "lm_sensors",
    "lsb-release",
    "lshw",
    "lsof",
    "man-db",
    "man-pages",
    "micro",
    "moreutils",
    "mpc",
    "mpd",
    "mpdris2",
    "mtools",
    "multitail",
    "neofetch",
    "neoss",
    "net-tools",
    "netkit-bsd-finger",
    "nfs-utils",
    "nitch",
    "nmap",
    "ntfs-3g",
    "orpie",
    "pamixer",
    "parted",
    "pass",
    "powertop",
    "psensor",
    "remind",
    "ripgrep",
    "samba",
    "screen",
    "scrub",
    "shc",
    "smbclient",
    "system-config-printer",
    "sysz",
    "termite",
    "the_silver_searcher",
    "tldr",
    "tlp",
    "tmux",
    "tmux-plugin-manager",
    "traceroute",
    "trash-cli",
    "ufiformat",
    "unipicker",
    "unison",
    "veracrypt",
    "vtop",
    "wipe",
    "woeusb",
    "ydotool",
    "zip",
]

