arch = [
    "clipman",
    "hyprland",
    "hyprpaper",
    "hyprpicker",
    "rofi-wayland",
    "swww",
    "waybar",
    "wayland",
    "wayland-protocols",
    "wayland-utils",
    "wl-clipboard",
    "wl-color-picker",
    "wlroots0.19",
    "wofi",
    "xorg-xwayland",
    "brightnessctl",
    "foot",
    "fuzzel",
    "grim",
    "mako",
    "niri",
    "slurp",
    "sway",
    "swaybg",
    "swayidle",
    "swaylock",
    "waybar",
    "wmenu",
    "xdg-desktop-portal-gnome",
    "xorg-xwayland",
]

